### ISSUE TITLE
Serial on Arduino IDE 2.3.3

### ISSUE THREAD

**Issue by riccalisci** [Xinyuan-LilyGO/T8-S3#1]
Hi there,
I have a T8-S3, I don't see anything on the serial monitor.
The programming is fine, but even with the example programs on the serial monitoe I don't see anything.

![Immagine 2024-11-19 161240](https://github.com/user-attachments/assets/5f79b940-50ca-4729-bc94-9eb8566468d9)

**Comment by Llgok** [comment]
@riccalisci 
You may need to enable this option in the Arduino IDE：
![image](https://github.com/user-attachments/assets/fa43be17-f8f7-4786-9b26-f6c7567c6e9b)

**Comment by riccalisci** [comment]
thanks a lot!!
